name: mero_school
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.72.0+122

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  http: ^0.13.4
  shared_preferences: ^2.0.11
  fluttertoast: ^8.0.9
  provider: ^6.0.1
#  rxdart: ^0.25.0
  lottie: ^1.2.1
  flutter_spinkit: ^5.1.0
  flutter_animation_progress_bar: ^2.0.1
#  smooth_star_rating: 1.1.1
  flutter_rating_bar: ^4.0.0
  flutter_speed_dial: ^6.0.0
  expansion_tile_card: ^2.0.0
  webview_flutter: ^3.0.4
  share: ^2.0.4
  youtube_player_flutter: ^8.0.0

#check better_player_controller.dart before udpating the library
#  better_player: ^0.0.79

  better_player:
    path: better_player


#
#  entrance:
#    path: entrance
#

#  flutter_html: any
#  flutter_icons: ^1.1.0
  flutter_font_icons: ^2.2.4
#  flutter_html: ^0.9.9
#  flutter_facebook_login: ^3.0.0
  google_sign_in: ^5.2.1
  flutter_placeholder_textlines: ^1.1.2
#  floor: ^1.0.0
#  moor_flutter: ^4.0.0
#  drift: ^1.1.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0

  get_it: ^7.2.0
  url_launcher: ^6.0.20
  image_picker: ^0.8.4+4
#  after_init: ^0.1.2
#  webview_flutter: ^3.0.0
  rxdart: ^0.27.3
  intl: ^0.17.0
  pull_to_refresh: ^2.0.0

  shimmer: ^2.0.0
  cached_network_image: ^3.2.0

  #firebase
  firebase_crashlytics: ^2.4.3
  firebase_analytics: ^9.0.3
  firebase_in_app_messaging: ^0.6.0+6
  firebase_dynamic_links: ^4.0.2
  firebase_messaging: ^11.2.3
  firebase_core: ^1.10.5
  flutter_local_notifications: ^11.0.1

  get_storage: ^2.0.3

  infinite_scroll_pagination: ^3.1.0
  http_interceptor: ^1.0.2
  snapping_sheet: ^3.1.0

#  flutter_html: ^0.9.7


  flutter_inappwebview: ^5.3.2
  maps_launcher: ^2.0.1

#  video_player: ^2.1.13
  video_player: 2.1.12

#  sign_in_with_apple: ^3.0.0
#  the_apple_sign_in: ^1.1.1

#  flutter_signinwithapple: ^0.0.1

#  in_app_purchase: ^1.0.8

  webengage_flutter: ^1.0.3
  flutter_inapp_purchase: ^5.1.2
  uni_links: ^0.5.1

  flutter_dropdown: ^1.0.0+hotfix.1
#  sms_retriever: ^1.0.0

  package_info_plus: ^1.3.0
  syncfusion_flutter_pdfviewer: ^20.2.50-beta
  in_app_update: ^3.0.0
  sign_in_with_apple:
    git:
      url: https://github.com/eduribas/dart_packages.git
      ref: ios_safari_fallback
      path: packages/sign_in_with_apple
  flutter_downloader: ^1.7.3
  permission_handler: ^10.0.1
  awesome_notifications: ^0.6.21
  flutter_facebook_auth: ^4.3.0
  flutter_signin_button: ^2.0.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  in_app_purchase: ^3.0.7

dev_dependencies:
#  floor_generator: any
  drift_dev: ^2.1.0
  build_runner: ^2.1.5
  flutter_native_splash: ^2.2.0+1

#dependency_overrides:
#  flutter_widget_from_html_core: ^0.8.3+1


flutter_native_splash:
  color: "#ffffff"
  image: 'assets/mero_school_logo.png'
  android: true
  ios: true

  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.retrofitdev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
     - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Sans
      fonts:
        - asset: fonts/google_sans_bold.ttf
        - asset: fonts/google_sans_light.ttf
        - asset: fonts/google_sans_medium.ttf
        - asset: fonts/google_sans_regular.ttf
        - asset: fonts/google_sans_thin.ttf





  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
